package managestore.server.service;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Singleton pattern: exactly one {@code SessionManager} for the whole
 * server process, since "is this username already logged in" only makes
 * sense as a single, shared source of truth across every connection thread.
 *
 * <p>Implements the brief's "no duplicate login from multiple computers"
 * requirement: {@link #tryLogin} is the sole gate a username must pass
 * before a connection is allowed to proceed past authentication.
 */
public final class SessionManager {

    private static final SessionManager INSTANCE = new SessionManager();

    private final Map<String, String> activeSessionIdByUsername = new ConcurrentHashMap<>();

    private SessionManager() {
    }

    public static SessionManager getInstance() {
        return INSTANCE;
    }

    /**
     * Attempts to bind {@code username} to {@code sessionId} (typically a
     * per-connection UUID generated by the ClientHandler). Returns false if
     * that username already has an active session elsewhere.
     */
    public boolean tryLogin(String username, String sessionId) {
        return activeSessionIdByUsername.putIfAbsent(username, sessionId) == null;
    }

    public void logout(String username) {
        activeSessionIdByUsername.remove(username);
    }
}
